<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/app/creativepharmacist.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">

                    <?php if(current_user_can('act_as_pharmacist')): ?>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="">Forums</a></li>
                        <li><a href="">Patients</a></li>
                        <li><a href="">Reports</a></li>
                        <li><a href="">Healthy Eats</a></li>
                        <li><a href="">Exercise</a></li>
                        <li><a href="">Resources</a></li>
                        <li><a href="<?php echo $this->serverUrl('blog') ?>">Blog</a></li>
                    </ul>
                    <?php else: ?>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="">Healthy Eats</a></li>
                        <li><a href="">Exercise</a></li>
                        <li><a href="">Resources</a></li>
                        <li><a href="">Support</a></li>
                    </ul>
                    <?php endif; ?>

                    <?php if(is_user_logged_in()): ?>
                    <ul class="nav navbar-right">
                        <li class=""><a href="<?php echo wp_logout_url($this->url('home')); ?>">Logout</a></li>
                    </ul>
                    <?php else: ?>
                    <ul class="nav navbar-right">
                        <li class=""><a href="<?php echo $this->url('login'); ?>">Login</a></li>
                    </ul>                    
                    <?php endif; ?>
                </div><!--/.nav-collapse -->


            </div>
        </nav>
        <div class="container">

            <? $messages = $this->flashMessenger()->getPluginFlashMessenger()->getErrorMessages();
            foreach($messages as $fMessage){  ?>
            <div class="alert alert-danger"><?php echo $fMessage; ?></div>
            <?php } ?>

            <?php 
            $messages = $this->flashMessenger()->getPluginFlashMessenger()->getSuccessMessages();
            foreach($messages as $fMessage) {  ?>
            <div class="alert alert-success"><?php echo $fMessage; ?></div>
            <?php } ?>

            <?php echo $this->content; ?>
            <hr class="clear" >
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
